.TH PREP 1
.SH NAME
prep \- SealFS log and keystream creation
.SH SYNOPSIS
.BI prep
.BI logfile
.BI kalpha
.BI kbeta 
.BI kfilesize
.SH DESCRIPTION
.I Prep
initalizes the SealFS log file and creates and fills the keystream files for a SealFS filesystem.
.SH STATUS
Exit status is 0 if the filesystem was created successfully and greater than 0 otherwise.
.SH SOURCE
.B sealfs/tools/prep.c and sealfs/tools/go/cmd/prep

There are two implementations, a C version and a go version. This man page refers to
both.
.SH SEE ALSO
verify(1), sealfs(5)
.SH BUGS
.I Prep
has no known bugs.
